name: Packagist

on:
  push:
    branches: [ main ]

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Packagist
        uses: php-actions/composer-push@v1
        with:
          packagist-token: ${{ secrets.PACKAGIST_TOKEN }}
          packagist-username: ${{ secrets.PACKAGIST_USERNAME }} 